admin/src/Entity/Messaging/Message.php
<?php

namespace App\Entity\Messaging;

use ApiPlatform\Core\Annotation\ApiFilter;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\DateFilter;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\ExistsFilter;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\BooleanFilter;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\OrderFilter;

use App\Filter\Messaging\NotLikeFilter;

use ApiPlatform\Core\Annotation\ApiResource;
use ApiPlatform\Core\Annotation\ApiSubresource;
use App\Util\Messaging\AppUtil;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\Self_;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Exception\UnsupportedException;
use App\Controller\MessageApprovalController;

/**
 * @ApiResource(
 *     attributes={
 *     "access_control"="is_granted('ROLE_USER')",
 *     "order"={"id": "DESC"}
 * },
 *     normalizationContext={"groups"={"read_message"}},
 *     denormalizationContext={"groups"={"write_message"}},
 *     itemOperations={
 *      "get",
 *      "post_message_approval"={
 *          "method"="POST",
 *          "path"="/messages/{id}/approval",
 *          "controller"=MessageApprovalController::class,
 *          "access_control"="is_granted('ROLE_ORG_ADMIN')",
 *          "normalization_context"={"groups"={"post_message_approval"}},
 *          "denormalization_context"={"groups"={"post_message_approval"}},
 *      },
 *      "put",
 *      "delete",
 *     }
 * )
 * @ApiFilter(SearchFilter::class, properties={"uuid": "exact", "sender.uuid": "exact", "optionSet.uuid": "uuid", "status":"exact", "type":"exact"})
 * @ApiFilter(BooleanFilter::class, properties={"senderMessageAdmin"})
 * @ApiFilter(NotLikeFilter::class)
 * @ApiFilter(ExistsFilter::class, properties={"approvalDecidedAt", "approvalDecisionReadAt"})
 *
 * @ORM\Entity(repositoryClass="App\Repository\Messaging\MessageRepository")
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\DiscriminatorMap({"free_on" = "App\Entity\Messaging\FreeOnMessage", "simple" = "App\Entity\Messaging\Message"})
 * @ORM\Table(name="messaging__message")
 * @ORM\HasLifecycleCallbacks()
 */
class Message
{
    const TYPE_SIMPLE = 'SIMPLE';
    const TYPE_FREE_ON = 'FREE_ON';

    const STATUS_DRAFT = 'MESSAGE_DRAFT';
    const STATUS_NEW = 'MESSAGE_NEW';
    const STATUS_PENDING_APPROVAL = 'MESSAGE_PENDING_APPROVAL';
    const STATUS_DELIVERY_REJECTED = 'DELIVERY_REJECTED';
    const STATUS_DELIVERY_IN_PROGRESS = 'DELIVERY_IN_PROGRESS';
    const STATUS_DELIVERY_SUCCESSFUL = 'DELIVERY_SUCCESSFUL';
    const STATUS_RECEIVED = 'MESSAGE_RECEIVED';

    const STATUS_READ = 'MESSAGE_READ';

    /**
     * @var int|null
     * @ORM\Id
     * @ORM\Column(type="integer",options={"unsigned":true})
     * @ORM\GeneratedValue(strategy="AUTO")
     * @Groups("read_message")
     */
    protected $id;

    /**
     * @var boolean $approved
     * @Groups("write_message")
     */
    protected $approved;

    /**
     * @var boolean $rejected
     * @Groups("write_message")
     */
    protected $rejected;

    /**
     * @return bool
     */
    public function isApproved(): bool
    {
        return $this->approved;
    }

    /**
     * @param bool $approved
     */
    public function setApproved(bool $approved): void
    {
        $this->approved = $approved;
        if ($approved && empty($this->approvalDecidedAt)) {
            $this->status = self::STATUS_NEW;
            $this->approvalDecidedAt = new \DateTime();
        }
    }

    /**
     * @return bool
     */
    public function isRejected(): bool
    {
        return $this->rejected;
    }

    /**
     * @param bool $rejected
     */
    public function setRejected(bool $rejected): void
    {
        $this->rejected = $rejected;
        if ($rejected && empty($this->approvalDecidedAt)) {
            $this->status = self::STATUS_DELIVERY_REJECTED;
            $this->approvalDecidedAt = new \DateTime();
        }
    }

    public function __construct()
    {
        $this->createdAt = new \DateTime();
        $this->status = self::STATUS_DRAFT;
        $this->deliveries = new ArrayCollection();
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function fixData()
    {
        if (empty($this->effectiveFrom)) {
            $this->effectiveFrom = $this->createdAt;
        }
        if (empty($this->expireAt)) {
            $this->expireAt = new \DateTime();
            $this->expireAt->modify('+30 days');
        }
        if ($this->senderMessageAdmin === null) {
            $this->senderMessageAdmin = $this->sender->isMessageAdmin();
        }
        if (empty($this->approvalDecidedAt) && $this->status === self::STATUS_DELIVERY_SUCCESSFUL) {
            $this->approvalDecidedAt = $this->createdAt;
        }
    }

    public function getDecisionStatus(): string
    {
        return $this->status;
    }

    public function getRecipientsByPage(): ?Collection
    {
        if (empty($this->conversation)) {
            $members = $this->organisation->getIndividualMembersByPage();
            if (empty($members)) {
                return null;
            }
        } else {
//            throw new UnsupportedException('Not yet implemented');
            $members = $this->conversation->getParticipants();
//                $this->status = self::STATUS_DELIVERY_SUCCESSFUL;
        }
        return $members;
    }

    public function commitDeliveries()
    {
        $message = $this;

        $deliveries = [];
        if (in_array($this->status, [self::STATUS_NEW, self::STATUS_DELIVERY_IN_PROGRESS])) {
            if (empty($members = $this->getRecipientsByPage())) {
                return false;
            }
            /** @var IndividualMember $member */
            foreach ($members as $member) {
                if ($member->isMessageDelivered($message)) { // || $member->getUuid() === $message->getSender()->getUuid() // can the sender receives his own messages
                    continue;
                }

                $recipient = $member;
                $delivery = Delivery::createInstance($this, $recipient);
                $deliveries[] = $delivery;
            }
        } else {
            return false;
        }

        return $deliveries;
    }

    /**
     * @ORM\PrePersist
     */
    public function initiateUuid()
    {
        if (empty($this->uuid)) {
            $this->uuid = AppUtil::generateUuid();
            if (empty($this->code)) {
                $this->code = $this->uuid;
            }
        }
    }

    /**
     * @Groups("write_message")
     */
    protected $published;

    public function setPublished(?bool $published): self
    {
        $this->published = $published;
        if ($published && $this->status === self::STATUS_DRAFT) {
            $this->setStatus(self::STATUS_NEW);
        }

        return $this;
    }

    /**
     * @ORM\Column(type="string", length=191)
     * @Groups("read_message")
     */
    protected $uuid;

    /**
     * @ORM\Column(type="datetime")
     * @Groups("read_message")
     */
    protected $createdAt;

    /**
     * @var Conversation
     * @ORM\ManyToOne(targetEntity="App\Entity\Messaging\Conversation", inversedBy="messages", cascade={"persist", "merge"})
     * @ORM\JoinColumn(name="id_conversation", referencedColumnName="id", onDelete="CASCADE")
     */
    protected $conversation;

    /**
     * @var Organisation
     * @ORM\ManyToOne(targetEntity="App\Entity\Messaging\Organisation", inversedBy="messages")
     * @ORM\JoinColumn(name="id_organisation", referencedColumnName="id")
     */
    protected $organisation;

    /**
     * @var IndividualMember
     * @ORM\ManyToOne(targetEntity="App\Entity\Messaging\IndividualMember", inversedBy="messages")
     * @ORM\JoinColumn(name="id_sender", referencedColumnName="id")
     */
    protected $sender;

    /**
     * @return string
     * @Groups("read_message")
     */
    public function getSenderUuid()
    {
        return $this->sender->getUuid();
    }

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Groups({"read_message", "write_message"})
     */
    protected $subject;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Groups({"read_message", "write_message"})
     */
    protected $body;

    /**
     * @var string
     * @ORM\Column(type="string", length=64, nullable=true)
     * @Groups("read_message")
     */
    protected $status;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Messaging\Delivery", mappedBy="message")
     * @ApiSubresource()
     */
    protected $deliveries;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Messaging\OptionSet", inversedBy="messages")
     * @Groups({"read_message", "write_message"})
     */
    protected $optionSet;

    /**
     * @var \DateTime|null
     * @ORM\Column(type="datetime", nullable=true)
     * @Groups({"read_message", "write_message"})
     */
    protected $expireAt;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Groups({"read_message", "write_message"})
     */
    protected $expireIn;
    /**
     * @ORM\Column(type="string", length=64, nullable=true)
     * @Groups({"read_message", "write_message"})
     */
    protected $expireInUnit;
    /**
     * @ORM\Column(type="string", length=255, nullable=true, options={"default":"SIMPLE"})
     */
    protected $type = self::TYPE_SIMPLE;

    /**
     * @var \DateTime|null
     * @ORM\Column(type="datetime", nullable=true)
     * @Groups({"read_message", "write_message"})
     */
    protected $effectiveFrom;

    /**
     * @ORM\Column(type="string", length=128, options={"default": "Asia/Singapore"})
     */
    protected $timezone = 'Asia/Singapore';

    /**

admin/templates/CRUD/decide.html.twig
{% extends '@SonataAdmin/CRUD/base_show.html.twig' %}
   {% block tab_menu_navbar_header %}
       {% if _navbar_title is not empty %}
           <div class="navbar-header" style="width: 100%; display: flex;">
               <div style="width:100%; display: flex; ">
                   {% if object.decisionStatus == 'APPROVED' %}
                       <span class="decision-status label label-success">APPROVED</span>
                       <div class="dropdown" style="margin-left: 8px;cursor: pointer;">
                           <div class="decision-status label label-default dropdown-toggle" data-toggle="dropdown"
                                id="changedecision" aria-haspopup="true" aria-expanded="false">Change Decision
                           </div>
                           <div class="dropdown-menu" aria-labelledby="changedecision">
                               <form action="" method="post" class="changedecision">
                                   <button type="submit" class="dropdown-item btn btn-default"
                                           style="margin: 0px 0px 5px 0px; width: 100%"
                                           data-action="{{ admin.generateObjectUrl('decide', object,{'action':'reject'}) }}">
                                       REJECT
                                   </button>
                                   <button type="submit" class="dropdown-item btn btn-default" style="width: 100%"
                                           data-action="{{ admin.generateObjectUrl('decide', object,{'action':'reset'}) }}">
                                       UNDO APPROVAL
                                   </button>

                               </form>
                           </div>
                       </div>

                   {% elseif  object.decisionStatus == 'REJECTED' %}
                       <span class="decision-status label label-danger">REJECTED</span>
                       <div class="dropdown" style="margin-left: 8px;cursor: pointer;">
                           <div class="decision-status label label-default dropdown-toggle" data-toggle="dropdown"
                                id="changedecision" aria-haspopup="true" aria-expanded="false">Change Decision
                           </div>
                           <div class="dropdown-menu" aria-labelledby="changedecision">
                               <form action="" method="post" class="changedecision">
                                   <button type="submit" class="dropdown-item btn btn-default"
                                           style="margin: 0px 0px 5px 0px; width: 100%"
                                           data-action="{{ admin.generateObjectUrl('decide', object,{'action':'approve'}) }}">
                                       APPROVE
                                   </button>
                                   <button type="submit" class="dropdown-item btn btn-default" style="width: 100%"
                                           data-action="{{ admin.generateObjectUrl('decide', object,{'action':'reset'}) }}">
                                       UNDO REJECTION
                                   </button>
                               </form>

                           </div>
                       </div>
                   {% endif %}


                   {% if admin.hasRoute('decide') %}

                       <form action="" method="post" class="decision-form"
                             style="width:100%; display: flex; align-items: center;">
                           {% set isApproveGranted =  admin.hasAccess('approve', object) %}
                           {% set isRejectGranted =  admin.hasAccess('reject', object) %}
                           {% if isApproveGranted is not empty and isRejectGranted is not empty %}
                               <button type="submit" class="decision-button btn btn-success"
                                       data-action="{{ admin.generateObjectUrl('decide', object,{'action':'approve'}) }}">
                                   APPROVE
                               </button>
                               <button type="submit" class="decision-button btn btn-danger"
                                       data-action="{{ admin.generateObjectUrl('decide', object,{'action':'reject'}) }}">
                                   REJECT
                               </button>
                           {% endif %}

                           {%- block decision_buttons -%} {% endblock %}
                           {% if object.status is not empty and object.status == 'NEW' %}
                               <input id="reviewer-remarks" name="decision-remarks"
                                      class="decision-remarks form-control"
                                      placeholder="Reviewer Remarks" value="{{ object.decisionRemarks }}"/>
                           {% elseif object.status == 'REJECTED' %}
                               <code>{{ object.decisionRemarks }}</code>
                           {% endif %}
                       </form>
                   {% endif %}
               </div>
           </div>
       {% endif %}
   {% endblock %}

{%- block javascripts -%}
    {{ parent() }}
    <script>
        (function ($) {
            $(document).ready(function ($) {
                $('.decision-form').on('submit', function () {

                });

                $("form button[type=submit]").click(function () {
                    $(this).parents("form").attr("action", $(this).data('action'));
                });

            });

        })(jQuery);
    </script>
{%- endblock javascripts -%}

{%- block stylesheets -%}
    {{ parent() }}
    <style>
        .navbar-collapse {
            display: none;
        }
    </style>
{%- endblock stylesheets -%}

admin/templates/CRUD/delete.html.twig
{% extends '@SonataAdmin/CRUD/delete.html.twig' %}

admin/templates/CRUD/list.html.twig
{% extends '@SonataAdmin/CRUD/list.html.twig' %}
{% block stylesheets %}
    {{ parent() }}
    <style>
        .box-footer .form-inline .checkbox {
            display: none;
        }
    </style>
{% endblock stylesheets %}